import { GenerateInput } from '@/types/content';

export function generateContent(input: GenerateInput) {
  const cta = 'Me chama no direct com a palavra IMÓVEL que eu te mando as opções.';
  if (input.format === 'Stories') return { type: 'Stories', stories: [1,2,3,4,5].map((n)=>({story:n,text:n===1?`Pergunta: ${input.audience}, qual seu maior desafio sobre ${input.product}?`:n===2?`Problema comum: muita gente atrasa resultados por falta de estratégia clara em ${input.niche}.`:n===3?`Dica prática: defina 1 meta semanal e 1 ação diária para ${input.goal.toLowerCase()}.`:n===4?`Bastidor/oferta: como eu ajudo com ${input.product} de forma personalizada.`:cta,objective:n===5?'Gerar directs':input.goal,visualSuggestion:n===5?'Print de conversa e seta para direct':'Vídeo selfie com legenda grande'})) };
  if (input.format === 'Post') return { type:'Post', title:`Como ${input.audience} pode ${input.goal.toLowerCase()} com ${input.product}`, caption:`Se você é ${input.audience}, este post é para você.\n\nNo nicho ${input.niche}, quem comunica com constância cresce. Hoje eu te mostro um caminho simples e ${input.tone.toLowerCase()} para acelerar resultados.\n\n1) Defina sua promessa principal\n2) Mostre prova real\n3) Chame para ação com clareza\n\n${input.extraNotes ?? ''}`, cta, hashtags:['#instagramparanegocios','#conteudodigital',`#${input.niche.replace(/\s+/g,'').toLowerCase()}`], imageSuggestion:'Foto profissional em ambiente real de atendimento' };
  if (input.format === 'Carrossel') return { type:'Carrossel', slides:[1,2,3,4,5,6].map((n)=>({title:n===1?`Pare de travar para postar sobre ${input.product}`:n===6?'Próximo passo':'Ponto estratégico',text:n===6?cta:`Slide ${n}: insight prático para ${input.goal.toLowerCase()} com tom ${input.tone.toLowerCase()}.`}))};
  if (input.format === 'Reels') return { type:'Reels', hook:`Você está a 1 ajuste de ${input.goal.toLowerCase()} no Instagram!`, scenes:[1,2,3,4].map((n)=>({scene:n,spokenText:`Cena ${n}: dica aplicada para ${input.audience}.`,screenText:n===1?'Erro comum' : n===4 ? 'Chamada final' : 'Passo prático'})), finalCta:cta};
  if (input.format === 'Calendário semanal') return { type:'Calendário semanal', days:['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'].map((d,i)=>({day:d,theme:`Tema ${i+1} para ${input.niche}`,format:i%2===0?'Stories':'Post',shortCaption:`Legenda curta focada em ${input.goal.toLowerCase()}.`,objective:input.goal}))};
  return { type:'Ideias rápidas', ideas:Array.from({length:15},(_,i)=>`${i+1}. Ideia para ${input.niche}: conteúdo rápido para ${input.goal.toLowerCase()} com foco em ${input.product}.`) };
}
